version: "2"

services:
  filebeat:
    container_name: filebeat
    hostname: filebeat
    image: docker.elastic.co/beats/filebeat:6.3.0
    user: root
    volumes:
      - ${PWD}/volumed-folder:/usr/share/filebeat/filebeat-volume
      - ${PWD}/volumed-folder/config/filebeat.yml:/usr/share/filebeat/filebeat.yml
    networks:
      - filebeat_net

networks:
  filebeat_net:
    external:
      name: elk_elk_net
