version: "2"

services:
  filebeat:
    container_name: filebeat
    hostname: filebeat
    image: docker.elastic.co/beats/filebeat:6.3.0
    user: root
    command: bash -c 'cd /usr/share/filebeat && rm filebeat.yml && cp filebeat-volume/config/filebeat.yml . && ./filebeat --once -e -c filebeat.yml -d "*"'
    volumes:
      - ${PWD}/volumed-folder:/usr/share/filebeat/filebeat-volume
    networks:
      - filebeat_net

networks:
  filebeat_net:
    external:
      name: elk_elk_net
