elk:
  container_name: sebp-elk
  image: sebp/elk
  ports:
    - "5601:5601"
    - "9200:9200"
    - "5044:5044"
  volumes:
    # The folder "logstash" lies in the root of this repository
    - /path/to/logstash/folder:/logstash
