version: '2'

services:
  elk:
    container_name: elk
    image: sebp/elk
    ports:
      - "5609:5601"
      - "9200:9200"
    volumes:
      - ${PWD}/volumed-folder/data:/logstash/data
      - ${PWD}/volumed-folder/config:/etc/logstash/conf.d
    networks:
      - elk_net

networks:
  elk_net:
    driver: bridge
