version: '3.7'

services:
  elk:
    container_name: elk
    image: sebp/elk
    ports:
      - "5602:5601"
      - "9200:9200"
      - "5044:5044"
    volumes:
      - logstash_dir:/logstash:ro

volumes:
  logstash_dir:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/londonelk/elk-docker/logstash
